PHOENIX-117 Phoenix is failing to establish connection on secure envs with NoClassDefFoundError
Change-Id: Ib4af2153dfe393252c9617bbce00440e48625767
(cherry picked from commit d015c2306dbb7cc98893d7c2e0f0faaa20bda271)